services:
  # infrastructure Services
  rwa-mongodb:
    extends:
      file: ./db/docker-compose.yml
      service: rwa-mongodb
    networks:
      - rwa-hub-network

  rwa-rabbitmq:
    extends:
      file: ./rabbitMQ/docker-compose.yml
      service: rwa-rabbitmq
    networks:
      - rwa-hub-network

  # Blockchain Services
  rwa-blockchain-indexer:
    extends:
      file: ./services/blockchain/indexer/docker-compose.yml
      service: rwa-blockchain-indexer
    networks:
      - rwa-hub-network
    depends_on:
      - rwa-mongodb
      - rwa-rabbitmq

 

networks:
  rwa-hub-network:
    external: true
    name: rwa-hub-network

volumes:
  # MongoDB volumes
  mongodb_data:
    name: rwa-mongodb-data
  mongodb_config:
    name: rwa-mongodb-config
  # RabbitMQ volumes
  rabbitmq_data:
    name: rwa-rabbitmq-data

  # Monitor volumes
  go-cache:
    name: rwa-blockchain-indexer-go-cache
  go-build-cache:
    name: rwa-blockchain-indexer-go-build-cache
